# Generated by Django 5.1.1 on 2024-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('roles', models.CharField(choices=[('EDUCATOR', 'Educator'), ('STUDENT', 'Student'), ('EMPLOYER', 'Employer')], max_length=50, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
